# Generated by Django 5.1.6 on 2025-02-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='image',
            field=models.BinaryField(editable=True),
        ),
    ]
